[package]
name = "git_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
crossterm = "0.25.0"
git2 = "0.16.0"
thiserror = "1.0.38"
